/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonDirectory;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author aditi
 */
public class CreateJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    public CreateJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        userProcessContainer = container;
        personDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfirstname = new javax.swing.JTextField();
        lblfirstname = new javax.swing.JLabel();
        lbllastname = new javax.swing.JLabel();
        lblsalary = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblheight = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        txtheight = new javax.swing.JTextField();
        lblstreetaddress = new javax.swing.JLabel();
        txtunitno = new javax.swing.JTextField();
        lblunitno = new javax.swing.JLabel();
        txtstreetaddress = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        lblzipcode = new javax.swing.JLabel();
        txtzipcode = new javax.swing.JTextField();
        lblphoneno = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        btncreate = new javax.swing.JButton();
        lblworkstreetaddress = new javax.swing.JLabel();
        lblworkunitno = new javax.swing.JLabel();
        lblworkcity = new javax.swing.JLabel();
        lblworkstate = new javax.swing.JLabel();
        lblworkzipcode = new javax.swing.JLabel();
        lblworkphoneno = new javax.swing.JLabel();
        txtworkunitno = new javax.swing.JTextField();
        txtworkstreetaddress = new javax.swing.JTextField();
        txtworkcity = new javax.swing.JTextField();
        txtworkstate = new javax.swing.JTextField();
        txtworkzipcode = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        lblCreatePerson = new javax.swing.JLabel();
        txtworkphnno = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();

        lblfirstname.setText("First Name");

        lbllastname.setText("Last Name");

        lblsalary.setText("Salary");

        lblage.setText("Age");

        lblgender.setText("Gender");

        lblheight.setText("Height");

        lblstreetaddress.setText("Street Address");

        lblunitno.setText("Unit Number");

        lblcity.setText("City");

        lblstate.setText("State");

        lblzipcode.setText("Zipcode");

        lblphoneno.setText("Phone Number");

        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });

        lblworkstreetaddress.setText("Street Address");

        lblworkunitno.setText("Unit Number");

        lblworkcity.setText("City");

        lblworkstate.setText("State");

        lblworkzipcode.setText("Zipcode");

        lblworkphoneno.setText("Phone Number");

        btnback.setText("<<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lblCreatePerson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCreatePerson.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreatePerson.setText("Create Person");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnback)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblworkstreetaddress)
                            .addComponent(txtworkstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblworkcity)
                            .addComponent(txtworkcity, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblworkzipcode)
                            .addComponent(txtworkzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtworkphnno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblworkphoneno))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblfirstname)
                                .addComponent(lblsalary)
                                .addComponent(lblstreetaddress)
                                .addComponent(lblcity)
                                .addComponent(lblzipcode)
                                .addComponent(txtsalary, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                .addComponent(txtstreetaddress)
                                .addComponent(txtcity)
                                .addComponent(txtzipcode, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbllastname)
                            .addComponent(lblage)
                            .addComponent(lblunitno)
                            .addComponent(lblstate)
                            .addComponent(lblphoneno)
                            .addComponent(txtstate, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(txtunitno)
                            .addComponent(txtage)
                            .addComponent(txtphoneno)
                            .addComponent(txtlastname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblgender)
                                    .addGap(185, 185, 185))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(78, 78, 78)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblworkunitno)
                                    .addComponent(txtworkunitno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblworkstate)
                                    .addComponent(txtworkstate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblheight))
                                .addGap(74, 74, 74))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(lblCreatePerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnback)
                        .addGap(7, 7, 7)
                        .addComponent(lblfirstname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblworkstreetaddress)
                            .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsalary)
                            .addComponent(lblage)
                            .addComponent(txtworkstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblworkcity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtworkcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblworkzipcode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtworkzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblworkphoneno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtworkphnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbllastname)
                            .addComponent(lblgender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblworkunitno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtworkunitno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblcity)
                                    .addComponent(lblstate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblzipcode)
                                    .addComponent(lblphoneno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblstreetaddress)
                                    .addComponent(lblunitno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtunitno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btncreate))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblworkstate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtworkstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblheight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(279, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        int age;
        int unitNo;
        int unitNoWA;
        int zipCode;
        int zipCodeWA;
        char gender;
        double height;
        float salary;
        long phoneNo;
        long phoneNoWA;
        
        Address homeAddress = new Address();
        Address workAddress = new Address();
        
        String fName = txtfirstname.getText();
        String lName = txtlastname.getText();
        String streetAddressHome = txtstreetaddress.getText();
        String streetAddressWork = txtworkstreetaddress.getText();
        String cityHome = txtcity.getText();
        String cityWork = txtworkcity.getText();
        String stateHome = txtstate.getText();
        String stateWork = txtworkstate.getText();
        
        //Null validations for attributes
        
        if (fName.isBlank() || lName.isBlank() || cityHome.isBlank() || cityWork.isBlank() || stateHome.isBlank() || stateWork.isBlank())
        {
           JOptionPane.showMessageDialog (this,"All fields are mandatory.","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
   
        
        try {
            age = Integer.parseInt(txtage.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please check the Age input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            salary = Float.parseFloat(txtsalary.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please check the Salary input. It should be a valid decimal number.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
}

        try {
            String genderStr = txtgender.getText();
            if (genderStr.length() != 1 || !(genderStr.equalsIgnoreCase("M") || genderStr.equalsIgnoreCase("F"))) {
                throw new IllegalArgumentException("Invalid gender input.");
            }
            gender = genderStr.charAt(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Gender input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            height = Float.parseFloat(txtheight.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please check the Height input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        try {
            unitNo = Integer.parseInt(txtunitno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Home Unit No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            unitNoWA = Integer.parseInt(txtworkunitno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Work Unit No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            zipCode = Integer.parseInt(txtzipcode.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Home Zip Code input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            zipCodeWA = Integer.parseInt(txtworkzipcode.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Work Zip Code input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            phoneNo = Long.parseLong(txtphoneno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Home Phone No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            phoneNoWA = Long.parseLong(txtworkphnno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Work Phone No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        homeAddress.setStreetAddress(streetAddressHome);
        homeAddress.setUnitNo(unitNo);
        homeAddress.setCity(cityHome);
        homeAddress.setState(stateHome);
        homeAddress.setZipCode(zipCode);
        homeAddress.setPhoneNo(phoneNo);
        
        workAddress.setStreetAddress(streetAddressWork);
        workAddress.setUnitNo(unitNoWA);
        workAddress.setCity(cityWork);
        workAddress.setState(stateWork);
        workAddress.setZipCode(zipCodeWA);
        workAddress.setPhoneNo(phoneNoWA);
        
        Person p = personDirectory.addPerson();
        p.setfName(fName);
        p.setlName(lName);
        p.setSalary(salary);
        p.setAge(age);
        p.setGender(gender);
        p.setHeight(height);
        p.setHomeAddress(homeAddress);
        p.setWorkAddress(workAddress);
        
        JOptionPane.showMessageDialog(this, "Account successfully created.", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        txtfirstname.setText("");
        txtlastname.setText("");
        txtsalary.setText("");
        txtage.setText("");
        txtgender.setText("");
        txtheight.setText("");
        txtstreetaddress.setText("");
        txtunitno.setText("");
        txtcity.setText("");
        txtstate.setText("");
        txtzipcode.setText("");
        txtphoneno.setText("");
        txtstreetaddress.setText("");
        txtworkunitno.setText("");
        txtworkphnno.setText("");
        txtworkstate.setText("");
        txtworkzipcode.setText("");
        txtworkphnno.setText("");
       

    }//GEN-LAST:event_btncreateActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncreate;
    private javax.swing.JLabel lblCreatePerson;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblfirstname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lbllastname;
    private javax.swing.JLabel lblphoneno;
    private javax.swing.JLabel lblsalary;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstreetaddress;
    private javax.swing.JLabel lblunitno;
    private javax.swing.JLabel lblworkcity;
    private javax.swing.JLabel lblworkphoneno;
    private javax.swing.JLabel lblworkstate;
    private javax.swing.JLabel lblworkstreetaddress;
    private javax.swing.JLabel lblworkunitno;
    private javax.swing.JLabel lblworkzipcode;
    private javax.swing.JLabel lblzipcode;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreetaddress;
    private javax.swing.JTextField txtunitno;
    private javax.swing.JTextField txtworkcity;
    private javax.swing.JTextField txtworkphnno;
    private javax.swing.JTextField txtworkstate;
    private javax.swing.JTextField txtworkstreetaddress;
    private javax.swing.JTextField txtworkunitno;
    private javax.swing.JTextField txtworkzipcode;
    private javax.swing.JTextField txtzipcode;
    // End of variables declaration//GEN-END:variables
}
