/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonDirectory;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.PersonDirectory;

/**
 *
 * @author aditi
 */
public class PersonMngAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonMngAreaJPanel
     */
    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    public PersonMngAreaJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        userProcessContainer= container;
        personDirectory= directory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnaddperson = new javax.swing.JButton();
        btnlistname = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        btnsearchforaddress = new javax.swing.JButton();

        btnaddperson.setText("Add Person");
        btnaddperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddpersonActionPerformed(evt);
            }
        });

        btnlistname.setText("List Person");
        btnlistname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistnameActionPerformed(evt);
            }
        });

        txtsearch.setText("Type name or street address");

        btnsearchforaddress.setText("Search for Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsearch)
                    .addComponent(btnlistname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnaddperson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsearchforaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(864, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnaddperson)
                .addGap(27, 27, 27)
                .addComponent(btnlistname)
                .addGap(75, 75, 75)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsearchforaddress)
                .addContainerGap(368, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddpersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddpersonActionPerformed
        CreateJPanel panel= new CreateJPanel (userProcessContainer, personDirectory);  
        userProcessContainer.add("CreateJPanel", panel);
        
        CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnaddpersonActionPerformed

    private void btnlistnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistnameActionPerformed
        ManagePerson panel = new ManagePerson(userProcessContainer, personDirectory);
        userProcessContainer.add("ManagePerson", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnlistnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddperson;
    private javax.swing.JButton btnlistname;
    private javax.swing.JButton btnsearchforaddress;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
