/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonDirectory;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author aditi
 */
    
public class ViewJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private Person person;
    
    public ViewJPanel(JPanel userProcessContainer, PersonDirectory personDirectory, Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        
        refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblworkzipcode = new javax.swing.JLabel();
        lblworkphoneno = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtworkunitno = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        txtworkstreetaddress = new javax.swing.JTextField();
        txtheight = new javax.swing.JTextField();
        txtworkcity = new javax.swing.JTextField();
        lblstreetaddress = new javax.swing.JLabel();
        txtworkstate = new javax.swing.JTextField();
        txtunitno = new javax.swing.JTextField();
        txtworkzipcode = new javax.swing.JTextField();
        lblunitno = new javax.swing.JLabel();
        txtstreetaddress = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        lblcity = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        lblzipcode = new javax.swing.JLabel();
        txtzipcode = new javax.swing.JTextField();
        txtfirstname = new javax.swing.JTextField();
        lblphoneno = new javax.swing.JLabel();
        lblfirstname = new javax.swing.JLabel();
        lbllastname = new javax.swing.JLabel();
        lblworkstreetaddress = new javax.swing.JLabel();
        lblsalary = new javax.swing.JLabel();
        lblworkunitno = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblworkcity = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblworkstate = new javax.swing.JLabel();
        lblheight = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        txtworkphnno = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        txtphoneno = new javax.swing.JTextField();

        lblworkzipcode.setText("Zipcode");

        lblworkphoneno.setText("Phone Number");

        lblstreetaddress.setText("Street Address");

        lblunitno.setText("Unit Number");

        btnback.setText("<<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lblcity.setText("City");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Create Person");

        lblstate.setText("State");

        lblzipcode.setText("Zipcode");

        lblphoneno.setText("Phone Number");

        lblfirstname.setText("First Name");

        lbllastname.setText("Last Name");

        lblworkstreetaddress.setText("Street Address");

        lblsalary.setText("Salary");

        lblworkunitno.setText("Unit Number");

        lblage.setText("Age");

        lblworkcity.setText("City");

        lblgender.setText("Gender");

        lblworkstate.setText("State");

        lblheight.setText("Height");

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        txtgender.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblworkcity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblworkstate)
                        .addGap(152, 152, 152))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtworkcity, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblworkzipcode))
                            .addComponent(txtworkzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblfirstname)
                            .addComponent(lblsalary)
                            .addComponent(lblgender)
                            .addComponent(lblstreetaddress)
                            .addComponent(lblcity)
                            .addComponent(lblzipcode)
                            .addComponent(txtsalary)
                            .addComponent(txtfirstname)
                            .addComponent(txtstreetaddress)
                            .addComponent(txtcity)
                            .addComponent(txtzipcode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblworkstreetaddress)
                            .addComponent(txtworkstreetaddress)
                            .addComponent(txtgender, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbllastname)
                            .addComponent(lblage)
                            .addComponent(lblheight)
                            .addComponent(lblunitno)
                            .addComponent(lblstate)
                            .addComponent(lblphoneno)
                            .addComponent(txtstate, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtunitno)
                            .addComponent(txtheight)
                            .addComponent(txtage)
                            .addComponent(lblworkunitno)
                            .addComponent(txtworkunitno)
                            .addComponent(txtlastname)
                            .addComponent(txtphoneno))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtworkstate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblworkphoneno)
                                    .addComponent(txtworkphnno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnsave)
                                .addGap(42, 42, 42)
                                .addComponent(btnupdate)
                                .addContainerGap(67, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnback)
                                    .addComponent(jLabel19)
                                    .addComponent(btnupdate))
                                .addGap(7, 7, 7)
                                .addComponent(lblfirstname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsalary)
                            .addComponent(lblage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lbllastname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblgender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblheight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblworkcity)
                    .addComponent(lblworkstate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstreetaddress)
                    .addComponent(lblunitno)
                    .addComponent(txtworkcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtworkstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtunitno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcity)
                            .addComponent(lblstate)
                            .addComponent(lblworkzipcode)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblworkphoneno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtworkzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtworkphnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblzipcode)
                    .addComponent(lblphoneno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblworkstreetaddress)
                    .addComponent(lblworkunitno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtworkunitno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtworkstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        userProcessContainer.remove(this);
        Component[] panelStack=userProcessContainer.getComponents();
        JPanel lastPanel =(JPanel)panelStack[panelStack.length-1];
        ManagePerson managePersonJPanel = (ManagePerson) lastPanel;
        managePersonJPanel.populateTable();

        
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        setViewMode();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        
        int age;
        int unitNo;
        int unitNoWA;
        int zipCode;
        int zipCodeWA;
        char gender;
        float salary;
        double height;
        long phoneNo;
        long phoneNoWA;
        
        
        Address homeAddress = new Address();
        Address workAddress = new Address();
        
        String firstName = txtfirstname.getText();
        String lastName = txtlastname.getText();
        String streetAddressHome = txtstreetaddress.getText();
        String streetAddressWork = txtworkstreetaddress.getText();
        String cityHome = txtcity.getText();
        String cityWork = txtworkcity.getText();
        String stateHome = txtstate.getText();
        String stateWork = txtworkstate.getText();
        
        //Null validations for attributes
        
        if (firstName.isBlank() || lastName.isBlank() || cityHome.isBlank() || cityWork.isBlank() || stateHome.isBlank() || stateWork.isBlank())
        {
           JOptionPane.showMessageDialog (this,"All fields are mandatory.","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        
        try {
            age = Integer.parseInt(txtage.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please check the Age input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            salary = Float.parseFloat(txtsalary.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please check the Salary input. It should be a valid decimal number.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
            }
        
        try {
            height = Double.parseDouble(txtheight.getText());
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please check the Height input. It should be a valid decimal number.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }

        
        try {
            String genderStr = txtgender.getText();
            if (genderStr.length() != 1 || !(genderStr.equalsIgnoreCase("M") || genderStr.equalsIgnoreCase("F"))) {
                throw new IllegalArgumentException("Invalid gender input.");
            }
            gender = genderStr.charAt(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Gender input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
      
        
        try {
            unitNo = Integer.parseInt(txtunitno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Home Unit No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            unitNoWA = Integer.parseInt(txtworkunitno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Work Unit No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            zipCode = Integer.parseInt(txtzipcode.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Home Zip Code input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            zipCodeWA = Integer.parseInt(txtworkzipcode.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Work Zip Code input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            phoneNo = Long.parseLong(txtphoneno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Home Phone No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            phoneNoWA = Long.parseLong(txtworkphnno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Work Phone No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        homeAddress.setStreetAddress(streetAddressHome);
        homeAddress.setUnitNo(unitNo);
        homeAddress.setCity(cityHome);
        homeAddress.setState(stateHome);
        homeAddress.setZipCode(zipCode);
        homeAddress.setPhoneNo(phoneNo);
        
        workAddress.setStreetAddress(streetAddressWork);
        workAddress.setUnitNo(unitNoWA);
        workAddress.setCity(cityWork);
        workAddress.setState(stateWork);
        workAddress.setZipCode(zipCodeWA);
        workAddress.setPhoneNo(phoneNoWA);
        
        person.setfName(firstName);
        person.setlName(lastName);
        person.setAge(age);
        person.setGender(gender);
        person.setSalary(salary);
        person.setHeight(HEIGHT);
        person.setHomeAddress(homeAddress);
        person.setWorkAddress(workAddress);
        
        JOptionPane.showMessageDialog(this, "Account successfully updated.", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        setViewMode();
    


   

   

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
      setEditMode();
    }//GEN-LAST:event_btnupdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblfirstname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lbllastname;
    private javax.swing.JLabel lblphoneno;
    private javax.swing.JLabel lblsalary;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstreetaddress;
    private javax.swing.JLabel lblunitno;
    private javax.swing.JLabel lblworkcity;
    private javax.swing.JLabel lblworkphoneno;
    private javax.swing.JLabel lblworkstate;
    private javax.swing.JLabel lblworkstreetaddress;
    private javax.swing.JLabel lblworkunitno;
    private javax.swing.JLabel lblworkzipcode;
    private javax.swing.JLabel lblzipcode;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreetaddress;
    private javax.swing.JTextField txtunitno;
    private javax.swing.JTextField txtworkcity;
    private javax.swing.JTextField txtworkphnno;
    private javax.swing.JTextField txtworkphoneno;
    private javax.swing.JTextField txtworkphoneno1;
    private javax.swing.JTextField txtworkphoneno2;
    private javax.swing.JTextField txtworkstate;
    private javax.swing.JTextField txtworkstreetaddress;
    private javax.swing.JTextField txtworkunitno;
    private javax.swing.JTextField txtworkzipcode;
    private javax.swing.JTextField txtzipcode;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
        
        txtfirstname.setText(person.getfName());
        txtlastname.setText(person.getlName());
        txtage.setText(Integer.toString(person.getAge()));
        txtgender.setText(Character.toString(person.getGender()));
        txtsalary.setText(Float.toString(person.getSalary()));
        txtheight.setText(Double.toString(person.getHeight()));
        txtstreetaddress.setText(person.getHomeAddress().getStreetAddress());
        txtunitno.setText(Integer.toString(person.getHomeAddress().getUnitNo()));
        txtcity.setText(person.getHomeAddress().getCity());
        txtstate.setText(person.getHomeAddress().getState());
        txtzipcode.setText(Integer.toString(person.getHomeAddress().getZipCode()));
        txtphoneno.setText(Long.toString(person.getHomeAddress().getPhoneNo()));
        txtworkstreetaddress.setText(person.getWorkAddress().getStreetAddress());
        txtworkunitno.setText(Integer.toString(person.getWorkAddress().getUnitNo()));
        txtworkcity.setText(person.getWorkAddress().getCity());
        txtworkstate.setText(person.getWorkAddress().getState());
        txtworkzipcode.setText(Integer.toString(person.getWorkAddress().getZipCode()));
        txtworkphnno.setText(Long.toString(person.getWorkAddress().getPhoneNo()));
        
        
    }

    private void setViewMode() {
        txtfirstname.setEnabled(false);
        txtlastname.setEnabled(false);
        txtsalary.setEnabled(false);
        txtage.setEnabled(false);
        txtgender.setEnabled(false);
        txtheight.setEnabled(false);
        txtstreetaddress.setEnabled(false);
        txtunitno.setEnabled(false);
        txtcity.setEnabled(false);
        txtstate.setEnabled(false);
        txtzipcode.setEnabled(false);
        txtphoneno.setEnabled(false);
        txtworkstreetaddress.setEnabled(false);
        txtworkunitno.setEnabled(false);
        txtworkcity.setEnabled(false);
        txtworkstate.setEnabled(false);
        txtworkzipcode.setEnabled(false);
        txtworkphnno.setEnabled(false);
        
        btnsave.setEnabled(false);
        btnupdate.setEnabled(true);    
            

    }
    private void setEditMode() {
      txtfirstname.setEnabled(true);
      txtlastname.setEnabled(true);
      txtsalary.setEnabled(true);
      txtage.setEnabled(true);
      txtgender.setEnabled(true);
      txtheight.setEnabled(true);
      txtstreetaddress.setEnabled(true);
      txtunitno.setEnabled(true);  // Keep this one false
      txtcity.setEnabled(true);
      txtstate.setEnabled(true);
      txtzipcode.setEnabled(true);
      txtphoneno.setEnabled(true);
      txtworkstreetaddress.setEnabled(true);
      txtworkunitno.setEnabled(true);
      txtworkcity.setEnabled(true);
      txtworkstate.setEnabled(true);
      txtworkzipcode.setEnabled(true);
      txtworkphnno.setEnabled(true);

      btnsave.setEnabled(true);  // Enabling the save button
      btnupdate.setEnabled(false);


    }
}
