/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonDirectory;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author aditi
 */
    
public class ViewJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private Person person;
    
    public ViewJPanel(JPanel userProcessContainer, PersonDirectory personDirectory, Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        
        refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblfirstname = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        lbllastname = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        lblage = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        lblheight = new javax.swing.JLabel();
        txtheight = new javax.swing.JTextField();
        lblgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        lblsalary = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblstreetaddress = new javax.swing.JLabel();
        txtstreetaddress = new javax.swing.JTextField();
        lblunitno = new javax.swing.JLabel();
        txtunitno = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        txtstate = new javax.swing.JTextField();
        lblcity = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lblzipcode = new javax.swing.JLabel();
        txtzipcode = new javax.swing.JTextField();
        lblphoneno = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblworkstreetaddress = new javax.swing.JLabel();
        txtworkstreetaddress = new javax.swing.JTextField();
        lblworkunitno = new javax.swing.JLabel();
        txtworkunitno = new javax.swing.JTextField();
        lblworkstate = new javax.swing.JLabel();
        txtworkstate = new javax.swing.JTextField();
        lblworkcity = new javax.swing.JLabel();
        txtworkcity = new javax.swing.JTextField();
        lblworkzipcode = new javax.swing.JLabel();
        txtworkzipcode = new javax.swing.JTextField();
        lblworkphoneno = new javax.swing.JLabel();
        txtworkphnno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(255, 255, 204));
        setLayout(null);

        btnback.setText("<<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback);
        btnback.setBounds(31, 31, 82, 23);

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        add(btnsave);
        btnsave.setBounds(540, 460, 72, 23);

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate);
        btnupdate.setBounds(410, 460, 72, 23);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Person Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N

        lblfirstname.setText("First Name");

        lbllastname.setText("Last Name");

        lblage.setText("Age");

        lblheight.setText("Height");

        lblgender.setText("Gender");

        lblsalary.setText("Salary");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblfirstname)
                .addGap(216, 216, 216)
                .addComponent(lbllastname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblage)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblheight)
                .addGap(224, 224, 224)
                .addComponent(lblgender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblsalary)
                .addGap(90, 90, 90))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtheight)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfirstname)
                    .addComponent(lbllastname)
                    .addComponent(lblage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblheight)
                    .addComponent(lblgender)
                    .addComponent(lblsalary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(151, 6, 747, 130);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N

        lblstreetaddress.setText("Street Address");

        lblunitno.setText("Unit Number");

        lblstate.setText("State");

        lblcity.setText("City");

        lblzipcode.setText("Zipcode");

        lblphoneno.setText("Phone Number");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblstreetaddress)
                .addGap(189, 189, 189)
                .addComponent(lblunitno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblstate)
                .addGap(92, 92, 92))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblcity)
                .addGap(225, 225, 225)
                .addComponent(lblzipcode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblphoneno)
                .addGap(66, 66, 66))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtunitno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtphoneno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblstreetaddress)
                    .addComponent(lblunitno)
                    .addComponent(lblstate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtunitno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcity)
                    .addComponent(lblzipcode)
                    .addComponent(lblphoneno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(jPanel2);
        jPanel2.setBounds(150, 140, 747, 150);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Work Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N

        lblworkstreetaddress.setText("Street Address");

        lblworkunitno.setText("Unit Number");

        lblworkstate.setText("State");

        lblworkcity.setText("City");

        lblworkzipcode.setText("Zipcode");

        lblworkphoneno.setText("Phone Number");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblworkstreetaddress)
                .addGap(171, 171, 171)
                .addComponent(lblworkunitno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblworkstate)
                .addGap(86, 86, 86))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(lblworkcity)
                .addGap(215, 215, 215)
                .addComponent(lblworkzipcode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblworkphoneno)
                .addGap(57, 57, 57))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtworkstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtworkcity, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtworkunitno, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(txtworkzipcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtworkstate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtworkphnno, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblworkstreetaddress)
                    .addComponent(lblworkunitno)
                    .addComponent(lblworkstate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtworkstreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtworkunitno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtworkstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblworkcity)
                    .addComponent(lblworkzipcode)
                    .addComponent(lblworkphoneno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtworkzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtworkphnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtworkcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        add(jPanel3);
        jPanel3.setBounds(150, 300, 747, 150);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("View Person");
        add(jLabel1);
        jLabel1.setBounds(31, 171, 100, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        userProcessContainer.remove(this);
        Component[] panelStack=userProcessContainer.getComponents();
        JPanel lastPanel =(JPanel)panelStack[panelStack.length-1];
        ManagePerson managePersonJPanel = (ManagePerson) lastPanel;
        managePersonJPanel.populateTable();

        
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        setViewMode();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        
        int age;
        int unitNo;
        int unitNoWA;
        int zipCode;
        int zipCodeWA;
        char gender;
        float salary;
        double height;
        long phoneNo;
        long phoneNoWA;
        
        
        Address homeAddress = new Address();
        Address workAddress = new Address();
        
        String firstName = txtfirstname.getText();
        String lastName = txtlastname.getText();
        String streetAddressHome = txtstreetaddress.getText();
        String streetAddressWork = txtworkstreetaddress.getText();
        String cityHome = txtcity.getText();
        String cityWork = txtworkcity.getText();
        String stateHome = txtstate.getText();
        String stateWork = txtworkstate.getText();
        
        //Null validations for attributes
        
        if (firstName.isBlank() || lastName.isBlank() || cityHome.isBlank() || cityWork.isBlank() || stateHome.isBlank() || stateWork.isBlank())
        {
           JOptionPane.showMessageDialog (this,"All fields are mandatory.","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        
        try {
            age = Integer.parseInt(txtage.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please check the Age input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            salary = Float.parseFloat(txtsalary.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please check the Salary input. It should be a valid decimal number.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
            }
        
        try {
            height = Double.parseDouble(txtheight.getText());
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please check the Height input. It should be a valid decimal number.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
        }

        
        try {
            String genderStr = txtgender.getText();
            if (genderStr.length() != 1 || !(genderStr.equalsIgnoreCase("M") || genderStr.equalsIgnoreCase("F"))) {
                throw new IllegalArgumentException("Invalid gender input.");
            }
            gender = genderStr.charAt(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Gender input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
      
        
        try {
            unitNo = Integer.parseInt(txtunitno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Home Unit No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            unitNoWA = Integer.parseInt(txtworkunitno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Work Unit No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            zipCode = Integer.parseInt(txtzipcode.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Home Zip Code input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            zipCodeWA = Integer.parseInt(txtworkzipcode.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Work Zip Code input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            phoneNo = Long.parseLong(txtphoneno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Home Phone No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            phoneNoWA = Long.parseLong(txtworkphnno.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Work Phone No. input.","Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        homeAddress.setStreetAddress(streetAddressHome);
        homeAddress.setUnitNo(unitNo);
        homeAddress.setCity(cityHome);
        homeAddress.setState(stateHome);
        homeAddress.setZipCode(zipCode);
        homeAddress.setPhoneNo(phoneNo);
        
        workAddress.setStreetAddress(streetAddressWork);
        workAddress.setUnitNo(unitNoWA);
        workAddress.setCity(cityWork);
        workAddress.setState(stateWork);
        workAddress.setZipCode(zipCodeWA);
        workAddress.setPhoneNo(phoneNoWA);
        
        person.setfName(firstName);
        person.setlName(lastName);
        person.setAge(age);
        person.setGender(gender);
        person.setSalary(salary);
        person.setHeight(HEIGHT);
        person.setHomeAddress(homeAddress);
        person.setWorkAddress(workAddress);
        
        JOptionPane.showMessageDialog(this, "Account successfully updated.", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        setViewMode();
    


   

   

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
      setEditMode();
    }//GEN-LAST:event_btnupdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblfirstname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lbllastname;
    private javax.swing.JLabel lblphoneno;
    private javax.swing.JLabel lblsalary;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lblstreetaddress;
    private javax.swing.JLabel lblunitno;
    private javax.swing.JLabel lblworkcity;
    private javax.swing.JLabel lblworkphoneno;
    private javax.swing.JLabel lblworkstate;
    private javax.swing.JLabel lblworkstreetaddress;
    private javax.swing.JLabel lblworkunitno;
    private javax.swing.JLabel lblworkzipcode;
    private javax.swing.JLabel lblzipcode;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtheight;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtstate;
    private javax.swing.JTextField txtstreetaddress;
    private javax.swing.JTextField txtunitno;
    private javax.swing.JTextField txtworkcity;
    private javax.swing.JTextField txtworkphnno;
    private javax.swing.JTextField txtworkphoneno;
    private javax.swing.JTextField txtworkphoneno1;
    private javax.swing.JTextField txtworkphoneno2;
    private javax.swing.JTextField txtworkstate;
    private javax.swing.JTextField txtworkstreetaddress;
    private javax.swing.JTextField txtworkunitno;
    private javax.swing.JTextField txtworkzipcode;
    private javax.swing.JTextField txtzipcode;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
        
        txtfirstname.setText(person.getfName());
        txtlastname.setText(person.getlName());
        txtage.setText(Integer.toString(person.getAge()));
        txtgender.setText(Character.toString(person.getGender()));
        txtsalary.setText(Float.toString(person.getSalary()));
        txtheight.setText(Double.toString(person.getHeight()));
        txtstreetaddress.setText(person.getHomeAddress().getStreetAddress());
        txtunitno.setText(Integer.toString(person.getHomeAddress().getUnitNo()));
        txtcity.setText(person.getHomeAddress().getCity());
        txtstate.setText(person.getHomeAddress().getState());
        txtzipcode.setText(Integer.toString(person.getHomeAddress().getZipCode()));
        txtphoneno.setText(Long.toString(person.getHomeAddress().getPhoneNo()));
        txtworkstreetaddress.setText(person.getWorkAddress().getStreetAddress());
        txtworkunitno.setText(Integer.toString(person.getWorkAddress().getUnitNo()));
        txtworkcity.setText(person.getWorkAddress().getCity());
        txtworkstate.setText(person.getWorkAddress().getState());
        txtworkzipcode.setText(Integer.toString(person.getWorkAddress().getZipCode()));
        txtworkphnno.setText(Long.toString(person.getWorkAddress().getPhoneNo()));
        
        
    }

    private void setViewMode() {
        txtfirstname.setEnabled(false);
        txtlastname.setEnabled(false);
        txtsalary.setEnabled(false);
        txtage.setEnabled(false);
        txtgender.setEnabled(false);
        txtheight.setEnabled(false);
        txtstreetaddress.setEnabled(false);
        txtunitno.setEnabled(false);
        txtcity.setEnabled(false);
        txtstate.setEnabled(false);
        txtzipcode.setEnabled(false);
        txtphoneno.setEnabled(false);
        txtworkstreetaddress.setEnabled(false);
        txtworkunitno.setEnabled(false);
        txtworkcity.setEnabled(false);
        txtworkstate.setEnabled(false);
        txtworkzipcode.setEnabled(false);
        txtworkphnno.setEnabled(false);
        
        btnsave.setEnabled(false);
        btnupdate.setEnabled(true);    
            

    }
    private void setEditMode() {
      txtfirstname.setEnabled(true);
      txtlastname.setEnabled(true);
      txtsalary.setEnabled(true);
      txtage.setEnabled(true);
      txtgender.setEnabled(true);
      txtheight.setEnabled(true);
      txtstreetaddress.setEnabled(true);
      txtunitno.setEnabled(true);  // Keep this one false
      txtcity.setEnabled(true);
      txtstate.setEnabled(true);
      txtzipcode.setEnabled(true);
      txtphoneno.setEnabled(true);
      txtworkstreetaddress.setEnabled(true);
      txtworkunitno.setEnabled(true);
      txtworkcity.setEnabled(true);
      txtworkstate.setEnabled(true);
      txtworkzipcode.setEnabled(true);
      txtworkphnno.setEnabled(true);

      btnsave.setEnabled(true);  // Enabling the save button
      btnupdate.setEnabled(false);


    }
}
