/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Persondetails;

/**
 *
 * @author aditi
 */
public class viewpersondetails extends javax.swing.JPanel {

    /**
     * Creates new form viewpersondetails
     */
    Persondetails persondetails;
    public viewpersondetails(Persondetails p) {
        initComponents();
        persondetails= p;
        
        displaypersondetails();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblview = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblfax = new javax.swing.JLabel();
        lbldriverlicno = new javax.swing.JLabel();
        lbldriverlicst = new javax.swing.JLabel();
        lblfirstname = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        txtst = new javax.swing.JTextField();
        txtzip = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txttelno = new javax.swing.JTextField();
        txtfax = new javax.swing.JTextField();
        txthobbies = new javax.swing.JTextField();
        lbladdr1 = new javax.swing.JLabel();
        lbladdr2 = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        lblstate = new javax.swing.JLabel();
        lblzip = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lbltelno = new javax.swing.JLabel();
        lbllang = new javax.swing.JLabel();
        lblhobbies = new javax.swing.JLabel();
        lbled = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        txtdrlst = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtdln = new javax.swing.JTextField();
        txtaddr1 = new javax.swing.JTextField();
        txtssn = new javax.swing.JTextField();
        txtaddr2 = new javax.swing.JTextField();
        txtlang = new javax.swing.JTextField();
        txted = new javax.swing.JTextField();
        txtvisatype = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        lbllastname = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        lblvisatype = new javax.swing.JLabel();

        lblview.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblview.setText("View Personal Details");

        lblemail.setText("Email");

        lblfax.setText("Fax Number");

        lbldriverlicno.setText("Drivers License Number");

        lbldriverlicst.setText("Drivers License State");

        lblfirstname.setText("First Name");

        txtfax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfaxActionPerformed(evt);
            }
        });

        lbladdr1.setText("Address Line 1");

        lbladdr2.setText("Address Line 2");

        lblssn.setText("Social Security Number");

        lblstate.setText("State");

        lblzip.setText("ZIP");

        lblcity.setText("City");

        lbltelno.setText("Telephone Number");

        lbllang.setText("Languages");

        lblhobbies.setText("Hobbies");

        lbled.setText("Education");

        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        lbllastname.setText("Last Name");

        lblgender.setText("Gender");

        lblphone.setText("Phone");

        lbldob.setText("DOB");

        lblvisatype.setText("Visa Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdln, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbldriverlicst, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdrlst, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(lbltelno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttelno)
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbldriverlicno, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblfirstname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblssn, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblstate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblzip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblcity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbladdr2)
                            .addComponent(lbladdr1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtfirstname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtaddr1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtaddr2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtzip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(147, 147, 147)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblfax, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbllang, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblhobbies, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbled, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbllastname, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblgender, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblphone, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbldob, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblvisatype, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtlastname)
                        .addComponent(txtphone)
                        .addComponent(txtfax)
                        .addComponent(txthobbies)
                        .addComponent(txtlang)
                        .addComponent(txted)
                        .addComponent(txtvisatype)
                        .addComponent(txtdob)
                        .addComponent(txtgender, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                    .addGap(27, 27, 27)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbladdr1, lbladdr2, lblcity, lbldriverlicno, lbldriverlicst, lblemail, lblfirstname, lblssn, lblstate, lblzip, txtaddr1, txtaddr2, txtcity, txtdln, txtdrlst, txtemail, txtfirstname, txtssn, txtst, txtzip});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbldob, lbled, lblfax, lblgender, lblhobbies, lbllang, lbllastname, lblphone, lbltelno, lblvisatype, txtdob, txted, txtfax, txtgender, txthobbies, txtlang, txtlastname, txtphone, txttelno, txtvisatype});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblview)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltelno)
                            .addComponent(txttelno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldriverlicst, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdrlst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbldriverlicno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbllastname)
                                .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(7, 7, 7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblphone)
                                .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(46, 46, 46)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblfax)
                        .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(lblssn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbladdr1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtaddr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addComponent(lbladdr2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblstate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblzip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtzip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblhobbies)
                                .addComponent(txthobbies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbllang)
                                .addComponent(txtlang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbled)
                                .addComponent(txtaddr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblvisatype)
                                .addComponent(txtvisatype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbldob)
                                .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblgender)
                                .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(63, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbldob, lbled, lblfax, lblgender, lblhobbies, lbllang, lbllastname, lblphone, lbltelno, lblvisatype, txtdob, txted, txtfax, txtgender, txthobbies, txtlang, txtlastname, txtphone, txttelno, txtvisatype});

    }// </editor-fold>//GEN-END:initComponents

    private void txtfaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfaxActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbladdr1;
    private javax.swing.JLabel lbladdr2;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lbldriverlicno;
    private javax.swing.JLabel lbldriverlicst;
    private javax.swing.JLabel lbled;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfax;
    private javax.swing.JLabel lblfirstname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblhobbies;
    private javax.swing.JLabel lbllang;
    private javax.swing.JLabel lbllastname;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lbltelno;
    private javax.swing.JLabel lblview;
    private javax.swing.JLabel lblvisatype;
    private javax.swing.JLabel lblzip;
    private javax.swing.JTextField txtaddr1;
    private javax.swing.JTextField txtaddr2;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtdln;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtdrlst;
    private javax.swing.JTextField txted;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txthobbies;
    private javax.swing.JTextField txtlang;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txtst;
    private javax.swing.JTextField txttelno;
    private javax.swing.JTextField txtvisatype;
    private javax.swing.JTextField txtzip;
    // End of variables declaration//GEN-END:variables

    private void displaypersondetails() {
        txtaddr1.setText(persondetails.getAadr1());
        txtaddr2.setText(persondetails.getAddr2());
        txtcity.setText(persondetails.getCity());
        txtdrlst.setText(persondetails.getDrlst());
        txtdln.setText(persondetails.getDrlno());
        txtdob.setText(persondetails.getDob());
        txted.setText(persondetails.getEd());
        txtemail.setText(persondetails.getEmail());
        txtfax.setText(persondetails.getFaxno());
        txtfirstname.setText(persondetails.getFirstname());
        txthobbies.setText(persondetails.getHobbies());
        txtlang.setText(persondetails.getLang());
        txtlastname.setText(persondetails.getLastname());
        txtssn.setText(persondetails.getSsn());
        txtst.setText(persondetails.getState());
        txtzip.setText(persondetails.getZip());
        txtphone.setText(persondetails.getPhone());
        txtgender.setText(persondetails.getGender());
        txtvisatype.setText(persondetails.getVisatype());
        txttelno.setText(persondetails.getTelno());
        
        
    }
}
